$(document).ready(function () {
    BindControls();
  });

  function BindControls() {
    var arrActions = [
      "AAPL (Apple Inc.)",
      "ABBV (AbbVie Inc.)", "ABT (Abbott Laboratories)", "ACN (Accenture plc)", "ADBE (Adobe Inc.)", "AFL (AFLAC Incorporated)",
      "AIG (American International Group, Inc.)", "ALL (The Allstate Corporation)", "AMAT (Applied Materials, Inc.)", "AMD (Advanced Micro Devices, Inc.)", "AMGN (Amgen Inc.)",
      "AMP (Ameriprise Financial, Inc.)", "AMT (American Tower Corporation (REIT))", "AMZN (Amazon.com, Inc.)", "ANTM (Anthem, Inc.)", "AON (Aon plc)",
      "AOS (A. O. Smith Corporation)", "APA (Apache Corporation)", "APD (Air Products and Chemicals, Inc.)", "APH (Amphenol Corporation)", "APTV (Aptiv PLC)",
      "ARE (Alexandria Real Estate Equities, Inc.)", "ATVI (Activision Blizzard, Inc.)", "AVB (AvalonBay Communities, Inc.)", "AVGO (Broadcom Inc.)", "AVY (Avery Dennison Corporation)",
      "AWK (American Water Works Company, Inc.)", "AXP (American Express Company)", "AZO (AutoZone, Inc.)", "BA (The Boeing Company)", "BAC (Bank of America Corporation)",
      "BAX (Baxter International Inc.)", "BDX (Becton, Dickinson and Company)", "BEN (Franklin Resources, Inc.)", "BIIB (Biogen Inc.)", "BK (The Bank of New York Mellon Corporation)",
      "BKNG (Booking Holdings Inc.)", "BLK (BlackRock, Inc.)", "BLL (Ball Corporation)", "BMY (Bristol-Myers Squibb Company)", "BR (Broadridge Financial Solutions, Inc.)",
      "BSX (Boston Scientific Corporation)", "BWA (BorgWarner Inc.)", "BXP (Boston Properties, Inc.)", "C (Citigroup Inc.)", "CAG (Conagra Brands, Inc.)",
      "CAH (Cardinal Health, Inc.)", "CAT (Caterpillar Inc.)", "CB (Chubb Limited)", "CBOE (Cboe Global Markets, Inc.)", "CBRE (CBRE Group, Inc.)",
      "CCI (Crown Castle International Corp.)", "CCL (Carnival Corporation & plc)", "CDNS (Cadence Design Systems, Inc.)", "CDW (CDW Corporation)", "CE (Celanese Corporation)",
      "CERN (Cerner Corporation)", "CF (CF Industries Holdings, Inc.)", "CFG (Citizens Financial Group, Inc.)", "CHD (Church & Dwight Co., Inc.)", "CHRW (C.H. Robinson Worldwide, Inc.)",
      "CHTR (Charter Communications, Inc.)", "CI (Cigna Corporation)", "CINF (Cincinnati Financial Corporation)", "CL (Colgate-Palmolive Company)", "CLX (The Clorox Company)",
      "CMA (Comerica Incorporated)", "CMCSA (Comcast Corporation)", "CME (CME Group Inc.)", "CMG (Chipotle Mexican Grill, Inc.)", "CMI (Cummins Inc.)",
      "CMS (CMS Energy Corporation)", "CNC (Centene Corporation)", "CNP (CenterPoint Energy, Inc.)", "COF (Capital One Financial Corporation)", "COG (Cabot Oil & Gas Corporation)",
      "COO (The Cooper Companies, Inc.)", "COP (ConocoPhillips)", "COST (Costco Wholesale Corporation)", "COTY (Coty Inc.)", "CPB (Campbell Soup Company)",
      "CPRT (Copart, Inc.)", "CRM (salesforce.com, inc.)", "CSCO (Cisco Systems, Inc.)", "CSX (CSX Corporation)", "CTAS (Cintas Corporation)",
      "CTLT (Catalent, Inc.)", "CTSH (Cognizant Technology Solutions Corporation)", "CTVA (Viatris Inc.)", "CTXS (Citrix Systems, Inc.)", "CVS (CVS Health Corporation)",
      "CVX (Chevron Corporation)", "CW (Curtiss-Wright Corporation)", "CXO (Concho Resources Inc.)", "D (Dominion Energy, Inc.)", "DAL (Delta Air Lines, Inc.)",
      "DD (DuPont de Nemours, Inc.)", "DE (Deere & Company)", "DFS (Discover Financial Services)", "DG (Dollar General Corporation)", "DGX (Quest Diagnostics Incorporated)",
      "DHI (D.R. Horton, Inc.)", "DHR (Danaher Corporation)", "DIS (The Walt Disney Company)", "DISCA (Discovery, Inc.)", "DISCK (Discovery, Inc.)",
      "DISH (DISH Network Corporation)", "DLR (Digital Realty Trust, Inc.)", "DLTR (Dollar Tree, Inc.)", "DOV (Dover Corporation)", "DOW (Dow Inc.)",
      "DRE (Duke Realty Corporation)", "DRI (Darden Restaurants, Inc.)", "DTE (DTE Energy Company)", "DUK (Duke Energy Corporation)", "DVA (DaVita Inc.)",
      "DVN (Devon Energy Corporation)", "DXC (DXC Technology Company)", "DXCM (DexCom, Inc.)", "EA (Electronic Arts Inc.)", "EBAY (eBay Inc.)",
      "ECL (Ecolab Inc.)", "ED (Consolidated Edison, Inc.)", "EFX (Equifax Inc.)", "EIX (Edison International)", "EL (The Estée Lauder Companies Inc.)",
      "EMN (Eastman Chemical Company)", "EMR (Emerson Electric Co.)", "ENPH (Enphase Energy, Inc.)", "EOG (EOG Resources, Inc.)", "EQIX (Equinix, Inc.)",
      "EQR (Equity Residential)", "ES (Eversource Energy)", "ESS (Essex Property Trust Inc.)", "ETN (Eaton Corporation plc)", "ETR (Entergy Corporation)",
      "EVRG (Evergy Inc.)", "EW (Edwards Lifesciences Corporation)", "EXC (Exelon Corporation)", "EXPD (Expeditors International of Washington Inc.)", "EXPE (Expedia Group Inc.)",
      "EXR (Extra Space Storage Inc.)", "F (Ford Motor Company)", "FANG (Diamondback Energy Inc.)", "FAST (Fastenal Company)", "FB (Meta Platforms Inc.)",
      "FBHS (Fortune Brands Home & Security Inc.)", "FCX (Freeport-McMoRan Inc.)", "FDX (FedEx Corporation)", "FE (FirstEnergy Corp.)", "FFIV (F5 Networks Inc.)",
      "FIS (Fidelity National Information Services Inc.)", "FISV (Fiserv Inc.)", "FITB (Fifth Third Bancorp)", "FLIR (FLIR Systems Inc.)", "FLS (Flowserve Corporation)",
      "FLT (FleetCor Technologies Inc.)", "FMC (FMC Corporation)", "FOX (Fox Corporation)", "FOXA (Fox Corporation)", "FRC (First Republic Bank)",
      "FRT (Federal Realty Investment Trust)", "FTNT (Fortinet Inc.)", "FTV (Fortive Corporation)", "GD (General Dynamics Corporation)", "GE (General Electric Company)",
      "GILD (Gilead Sciences Inc.)", "GIS (General Mills Inc.)", "GL (Corning Incorporated)", "GLW (Corning Incorporated)", "GM (General Motors Company)",
      "GOOG (Alphabet Inc.)", "GOOGL (Alphabet Inc.)", "GPC (Genuine Parts Company)", "GPN (Global Payments Inc.)", "GPS (Gap Inc.)",
      "GRMN (Garmin Ltd.)", "GS (The Goldman Sachs Group Inc)", "GWW (W.W. Grainger, Inc.)", "HAL (Halliburton Company)", "HAS (Hasbro, Inc.)",
      "HBAN (Huntington Bancshares Incorporated)", "HBI (Hanesbrands Inc.)", "HCA (HCA Healthcare, Inc.)", "HD (The Home Depot, Inc.)", "HES (Hess Corporation)",
      "HFC (HollyFrontier Corporation)", "HIG (The Hartford Financial Services Group, Inc.)", "HII (Huntington Ingalls Industries, Inc.)", "HLT (HLT Holdings Global, Inc.)", "HOLX (Hologic, Inc.)",
      "HON (Honeywell International Inc.)", "HPE (Hewlett Packard Enterprise Company)", "HPQ (HP Inc.)", "HRL (Hormel Foods Corporation)", "HSIC (Henry Schein, Inc.)",
      "HST (Host Hotels & Resorts, Inc.)", "HSY (The Hershey Company)", "HUM (Humana Inc.)", "HWM (Howmet Aerospace Inc.)", "IBM (International Business Machines Corporation)",
      "ICE (Intercontinental Exchange, Inc.)", "IDXX (IDEXX Laboratories, Inc.)", "IEX (IEX Group, Inc.)", "IFF (International Flavors & Fragrances Inc.)", "ILMN (Illumina, Inc.)",
      "INCY (Incyte Corporation)", "INFO (IHS Markit Ltd.)", "INTC (Intel Corporation)", "INTU (Intuit Inc.)", "IPG (The Interpublic Group of Companies, Inc.)",
      "IPGP (IPG Photonics Corporation)", "IQV (IQVIA Holdings Inc.)", "IR (Ingersoll Rand Inc.)", "IRM (Iron Mountain Incorporated)", "ISRG (Intuitive Surgical, Inc.)",
      "IT (Gartner, Inc.)", "ITW (Illinois Tool Works Inc.)", "IVZ (Invesco Ltd.)", "J (Jacobs Engineering Group Inc.)", "JBHT (J.B. Hunt Transport Services, Inc.)",
      "JCI (Johnson Controls International plc)", "JKHY (Jack Henry & Associates Inc)", "JNJ (Johnson & Johnson)", "JNPR (Juniper Networks Inc)", "JPM (JPMorgan Chase & Co.)",
      "JWN (Nordstrom Inc)", "K (Kellogg Co)", "KEY (KeyCorp)", "KEYS (Keysight Technologies Inc)", "KHC (Kraft Heinz Co)",
      "KIM (Kimco Realty Corp)", "KLAC (KLA Corp)", "KMB (Kimberly-Clark Corp)", "KMI (Kinder Morgan Inc)", "KMX (CarMax Inc)",
      "KO (Coca-Cola Co)", "KR (Kroger Co)", "KSS (Kohl's Corp)", "KSU (Kansas City Southern)", "L (Loews Corp)",
      "LHX (L3Harris Technologies Inc)", "LIN (Linde PLC)", "LKQ (LKQ Corp)", "LLY (Eli Lilly and Co)", "LMT (Lockheed Martin Corp)",
      "LNC (Lincoln National Corp)", "LNT (Alliant Energy Corp)", "LOW (Lowe's Companies Inc)", "LRCX (Lam Research Corp)", "LUMN (Lumen Technologies Inc)",
      "LUV (Southwest Airlines Co)", "LVS (Las Vegas Sands Corp)", "LW (Lamb Weston Holdings Inc)", "LYB (LyondellBasell Industries NV)", "LYV (Live Nation Entertainment Inc)",
      "M (Macy's Inc)", "MA (Mastercard Inc)", "MAA (Mid-America Apartment Communities Inc)", "MAC (Macerich Co)", "MAR (Marriott International Inc)",
      "MAS (Masco Corp)", "MCD (McDonald's Corp)", "MCHP (Microchip Technology Inc)", "MCK (McKesson Corp)", "M (Macy's Inc)",
      "MCO (Moody's Corp)", "MDLZ (Mondelez International Inc)", "MDT (Medtronic PLC)", "MET (MetLife Inc)", "MGM (MGM Resorts International)",
      "MHK (Mohawk Industries Inc)", "MKC (McCormick & Company Incorporated)", "MKTX (MarketAxess Holdings Inc)", "MLM (Martin Marietta Materials Inc)", "MMC (Marsh & McLennan Companies Inc)",
      "MMM (3M Co)", "MNST (Monster Beverage Corp)", "MO (Altria Group Inc)", "MOS (The Mosaic Company)", "MPC (Marathon Petroleum Corp)",
      "MPWR (Monolithic Power Systems Inc)", "MRK (Merck & Co. Inc)", "MRO (Marathon Oil Corp)", "MS (Morgan Stanley)", "MSCI (MSCI Inc)",
      "MSFT (Microsoft Corporation)", "MSI (Motorola Solutions Inc)", "MTB (M&T Bank Corporation)", "MTD (Mettler-Toledo International Inc)", "MU (Micron Technology Inc)",
      "MXIM (Maxim Integrated Products Inc)", "MYL (Mylan NV)", "NCLH (Norwegian Cruise Line Holdings Ltd)", "NDAQ (Nasdaq Inc)", "NEE (NextEra Energy Inc)",
      "NEM (Newmont Corporation)", "NEE (NextEra Energy Inc)", "NFLX (Netflix Inc)", "NI (NiSource Inc)", "NKE (Nike Inc)",
      "NKTR (Nektar Therapeutics)", "NLOK (NortonLifeLock Inc)", "NLSN (Nielsen Holdings plc)", "NOC (Northrop Grumman Corporation)", "NOV (National Oilwell Varco Inc)",
      "NOW (ServiceNow Inc)", "NRG (NRG Energy Inc)", "NSC (Norfolk Southern Corp)", "NTAP (NetApp Inc)", "NTRS (Northern Trust Corporation)",
      "NUE (Nucor Corporation)", "NVDA (NVIDIA Corporation)", "NVR (NVR, Inc.)", "NWL (Newell Brands Inc.)", "NWS (News Corporation)",
      "NWSA (News Corporation)", "O (Realty Income Corporation)", "ODFL (Old Dominion Freight Line, Inc.)", "OKE (ONEOK, Inc.)", "OMC (Omnicom Group Inc.)",
      "ORCL (Oracle Corporation)", "ORLY (O'Reilly Automotive, Inc.)", "OTIS (Otis Worldwide Corporation)", "OXY (Occidental Petroleum Corporation)", "PAYC (Paycom Software, Inc.)",
      "PAYX (Paychex, Inc.)", "PBCT (People's United Financial, Inc.)", "PCAR (PACCAR Inc)", "PEAK (Healthpeak Properties, Inc.)", "PEG (Public Service Enterprise Group Incorporated)",
      "PEP (PepsiCo, Inc.)", "PFE (Pfizer Inc.)", "PFG (Principal Financial Group, Inc.)", "PG (The Procter & Gamble Company)", "PGR (The Progressive Corporation)",
      "PH (Parker-Hannifin Corporation)", "PHM (PulteGroup, Inc.)", "PKG (Packaging Corporation of America)", "PKI (PerkinElmer, Inc.)", "PLD (Prologis, Inc.)",
      "PM (Philip Morris International Inc.)", "PNC (The PNC Financial Services Group, Inc.)", "PNR (Pentair plc)", "PNW (Pinnacle West Capital Corporation)", "POOL (Pool Corporation)",
      "PPG (PPG Industries, Inc.)", "PPL (PPL Corporation)", "PRGO (Perrigo Company plc)", "PRU (Prudential Financial, Inc.)", "PSA (Public Storage)",
      "PSX (Phillips 66)", "PVH (PVH Corp.)", "PWR (Quanta Services, Inc.)", "PXD (Pioneer Natural Resources Company)", "PYPL (PayPal Holdings, Inc.)",
      "QCOM (QUALCOMM Incorporated)", "QRVO (Qorvo, Inc.)", "RCL (Royal Caribbean Group)", "RE (Everest Re Group, Ltd.)", "REG (Regency Centers Corporation)",
      "REGN (Regeneron Pharmaceuticals, Inc.)", "RF (Regions Financial Corporation)", "RHI (Robert Half International Inc.)", "RJF (Raymond James Financial Inc.)", "RL (Ralph Lauren Corp)",
      "RMD (ResMed Inc.)", "ROK (Rockwell Automation Inc.)", "ROL (Rollins Inc.)", "ROP (Roper Technologies Inc)", "ROST (Ross Stores Inc.)",
      "RSG (Republic Services Inc.)", "RTX (Raytheon Technologies Corp)", "SBAC (SBA Communications Corp.)", "SBUX (Starbucks Corporation)", "SCHW (The Charles Schwab Corporation)",
      "SEE (Sealed Air Corp)", "SHW (The Sherwin-Williams Company)", "SIVB (SVB Financial Group)", "SJM (J.M. Smucker Company)", "SLB (Schlumberger NV)",
      "SLG (SL Green Realty Corp.)", "SNA (Snap-on Incorporated)", "SNPS (Synopsys Inc.)", "SO (Southern Company)", "SPG (Simon Property Group Inc.)",
      "SPGI (S&P Global Inc.)", "SRE (Sempra Energy)", "STE (STERIS plc)", "STT (State Street Corp)", "STX (Seagate Technology plc)",
      "STZ (Constellation Brands Inc.)", "SWK (Stanley Black & Decker Inc.)", "SWKS (Skyworks Solutions Inc.)", "SYF (Synchrony Financial)", "SYK (Stryker Corporation)",
      "SYY (Sysco Corporation)", "T (AT&T Inc.)", "TAP (Molson Coors Beverage Company)", "TDG (TransDigm Group Incorporated)", "TEL (TE Connectivity Ltd.)",
      "TER (Teradyne Inc.)", "TFC (Truist Financial Corporation)", "TFX (Teleflex Incorporated)", "TGT (Target Corporation)", "TIF (Tiffany & Co.)",
      "TJX (The TJX Companies Inc.)", "TMO (Thermo Fisher Scientific Inc.)", "TMUS (T-Mobile US Inc.)", "TPR (Tapestry Inc.)", "TROW (T. Rowe Price Group Inc.)",
      "TRV (The Travelers Companies, Inc.)", "TSCO (Tractor Supply Company)", "TSN (Tyson Foods, Inc.)", "TT (Trane Technologies plc)", "TTWO (Take-Two Interactive Software, Inc.)",
      "TWTR (Twitter, Inc.)", "TXN (Texas Instruments Incorporated)", "TXT (Textron Inc.)", "TYL (Tyler Technologies, Inc.)", "UA (Under Armour, Inc.)",
      "UAA (Under Armour, Inc.)", "UAL (United Airlines Holdings, Inc.)", "UDR (United Dominion Realty Trust, Inc.)", "UHS (Universal Health Services, Inc.)", "ULTA (Ulta Beauty, Inc.)",
      "UNH (UnitedHealth Group Incorporated)", "UNM (Unum Group)", "UNP (Union Pacific Corporation)", "UPS (United Parcel Service, Inc.)", "URI (United Rentals, Inc.)",
      "USB (U.S. Bancorp)", "V (Visa Inc.)", "VFC (V.F. Corporation)", "VIAC (ViacomCBS Inc.)", "VLO (Valero Energy Corporation)",
      "VMC (Vulcan Materials Company)", "VNO (Vornado Realty Trust)", "VRSK (Verisk Analytics, Inc.)", "VRSN (VeriSign, Inc.)", "VRTX (Vertex Pharmaceuticals Incorporated)",
      "VTR (Ventas, Inc.)", "VZ (Verizon Communications Inc.)", "WAB (Wabtec Corporation)", "WAT (Waters Corporation)", "WBA (Walgreens Boots Alliance, Inc.)",
      "WDC (Western Digital Corporation)", "WEC (WEC Energy Group, Inc.)", "WELL (Welltower Inc.)", "WFC (Wells Fargo & Company)", "WHR (Whirlpool Corporation)",
      "WLTW (Willis Towers Watson Public Limited Company)", "WM (Waste Management, Inc.)", "WMB (Williams Companies, Inc.)", "WMT (Walmart Inc.)", "WRB (W.R. Berkley Corporation)",
      "WRK (WestRock Company)", "WST (West Pharmaceutical Services, Inc.)", "WU (Western Union Co.)", "WY (Weyerhaeuser Co.)", "WYNN (Wynn Resorts Ltd.)",
      "XEL (Xcel Energy Inc.)", "XLNX (Xilinx Inc.)", "XOM (Exxon Mobil Corp.)", "XRAY (DENTSPLY SIRONA Inc.)", "XRX (Xerox Holdings Corp.)",
      "XYL (Xylem Inc.)", "YUM (YUM! BRANDS, INC.)", "ZBH (ZIMMER BIOMET HOLDINGS, INC.)", "ZBRA (ZEBRA TECHNOLOGIES CORPORATION)", "ZION (ZION BANCORPORATION, NATIONAL ASSOCIATION)",
      "ZTS (Zoetis Inc.)"
    ];

    $("#txtActions").autocomplete({
      source: arrActions,
      minLength: 1,
      delay:0,
    }).data("ui-autocomplete")._renderItem = function (ul, item) {
      let txt = String(item.value).replace(new RegExp(this.term, "gi"), "<b>$&</b>");
      return $("<li></li>")
        .data("ui-autocomplete-item", item)
        .append("<a>" + txt + "</a>")
        .appendTo(ul);
    };
  }